### ISSUE TITLE
run errors

### ISSUE THREAD

**Issue by Thanh-Binh** [Blimpyway/CartPoleChallenge#1]
Hi,
I have the following errors:
binh@NUPIC:~/experiments/openAI/CartPoleChallenge$ python3 cp_vmap_ovenc.py
SDR size is 120
Traceback (most recent call last):
  File "/home/binh/experiments/openAI/CartPoleChallenge/cp_vmap_ovenc.py", line 263, in <module>
    episodes = p.train()
  File "/home/binh/experiments/openAI/CartPoleChallenge/cp_vmap_ovenc.py", line 224, in train
    solved = one_round(render = render, learning = True) 
  File "/home/binh/experiments/openAI/CartPoleChallenge/cp_vmap_ovenc.py", line 203, in one_round
    action = pick_action(obs)
  File "/home/binh/experiments/openAI/CartPoleChallenge/cp_vmap_ovenc.py", line 154, in pick_action
    sdr = to_sdr(obs)
  File "/home/binh/experiments/openAI/CartPoleChallenge/cp_vmap_ovenc.py", line 89, in sdr
    d = dense(np.array(vals, dtype = np.float32))
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

Did I do something wrong here? Thanks

**Comment by Blimpyway** [comment]
Nope, gym package is a mess, the API was recently radically changed then dumped - no longer supported or maintained. 

So for now I'll add a requirements.txt which anyone willing to see the demos will have to install in a new virtualenv

**Comment by Blimpyway** [comment]
Ok, now the .py files are changed to run with current gym (0.26.2) api. 

See README.txt
